export const ROUTES = {
  public: {
    home: '/',
    about: '/about',
    contact: '/contact',
    pricing: '/pricing',
    successStories: '/success-stories',
    terms: '/terms',
    privacy: '/privacy-policy',
  },
  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyOtp: '/verify',
  },
  dashboard: {
    root: '/dashboard',
    profile: '/dashboard/profile',
    editProfile: '/dashboard/edit-profile',
    matches: '/dashboard/matches',
    preferences: '/dashboard/preferences',
    chat: '/dashboard/chat',
    shortlist: '/dashboard/shortlist',
    interests: '/dashboard/interests',
    notifications: '/dashboard/notifications',
    subscription: '/dashboard/subscription',
    settings: '/dashboard/settings',
  },
  admin: {
    login: '/admin/login',
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    approvals: '/admin/approvals',
    reports: '/admin/reports',
    subscriptions: '/admin/subscriptions',
    notifications: '/admin/notifications',
    analytics: '/admin/analytics',
    settings: '/admin/settings',
  },
};
